version: '3.8'

services: 
  api:
    image: easyscoreboard:1.2
    ports: 
      - 5000:5000
    volumes: 
      - ./app:/usr/src/app/app
    restart: always
  
  database:
      environment: 
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: easyscoreboard
      env_file: .env
      image: postgres:latest
      ports: 
        - 5405:5432
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data