version: '3.8'

services:
  api:
    build: .
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - mynetwork

  database:
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: easyscoreboard
      env_file: .env
      image: postgres:latest
      ports:
        - 5432:5432
      expose:
        - 5432
      volumes:
        - ~/dockerdata/postgresql:/var/lib/postgresql/data
      restart: always
      networks:
       - mynetwork

  frontend:
    ports:
      - 3000:3000
    build:
      context: ../easyscoreboard-frontend
    env_file:
      - ../easyscoreboard-frontend/.env
    command: npm run dev
    volumes:
      - ../easyscoreboard-frontend:/usr/src
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - database
    networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge