"""empty message

Revision ID: 1a8080af7608
Revises: 765d59f7e0da
Create Date: 2021-04-04 14:09:06.591450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8080af7608'
down_revision = '765d59f7e0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'code')
    # ### end Alembic commands ###
