"""empty message

Revision ID: 357358de9c9e
Revises: 
Create Date: 2021-03-03 00:03:18.921880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357358de9c9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('participants_score_key', 'participants', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('participants_score_key', 'participants', ['score'])
    # ### end Alembic commands ###
