"""empty message

Revision ID: 4ab027d52a88
Revises: b3c0796cf84b
Create Date: 2021-04-05 23:19:21.422572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab027d52a88'
down_revision = 'b3c0796cf84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    op.alter_column('participants', 'code',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participants', 'code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('boards', 'code',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    # ### end Alembic commands ###
