"""empty message

Revision ID: 765d59f7e0da
Revises: c44f04da2c98
Create Date: 2021-04-04 14:06:31.969893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765d59f7e0da'
down_revision = 'c44f04da2c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('code', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'code')
    # ### end Alembic commands ###
