"""empty message

Revision ID: b3c0796cf84b
Revises: cb3734cd0bef
Create Date: 2021-04-05 23:15:25.606929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c0796cf84b'
down_revision = 'cb3734cd0bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_boards_code'), 'boards', ['code'], unique=True)
    op.create_index(op.f('ix_participants_code'), 'participants', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_code'), table_name='participants')
    op.drop_index(op.f('ix_boards_code'), table_name='boards')
    # ### end Alembic commands ###
