"""empty message

Revision ID: c99c554a08d8
Revises: 8a8aecf95056
Create Date: 2021-04-04 17:29:55.888604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99c554a08d8'
down_revision = '8a8aecf95056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'code')
    # ### end Alembic commands ###
