"""empty message

Revision ID: cb3734cd0bef
Revises: 
Create Date: 2021-04-05 23:09:13.493542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3734cd0bef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('code', sa.String(length=8), nullable=True))
    op.add_column('participants', sa.Column('code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'code')
    op.drop_column('boards', 'code')
    # ### end Alembic commands ###
